Add Python 3.12 related updates
wichert/lingua pull request #110
Opened 2023-10-10 17:08 UTC by arkid15r

Resolves #109 

Add Python 3.12 related updates:
  - Use Python 3.8-3.12 for test matrix
  - Bump GH action versions
  - Fix configparser SafeConfigParser name issue (the initial one)
  - Replace pkg_resources with importlib.metadata

The 3.12 test job will fail due to a similar issue -- I'll revisit this if needed later after https://github.com/malthe/chameleon/issues/379 is addressed.

I also recommend migrating the PyPI publisher to [OIDC's short lived tokens](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi).

2023-11-14 13:11 UTC, sallner reviewed
Thanks for the work. I support those changes and would hope that they get merged and released soon.

2023-11-14 13:11 UTC, sallner commented on src/lingua/extract.py
>      from ConfigParser import SafeConfigParser
As this is a pattern to support Python 2 it might as well be a good idea to just use the Python 3 variant.

2023-11-14 13:11 UTC, sallner commented on src/lingua/extractors/__init__.py
> +    from importlib_metadata import entry_points
To prevent the same issue as with configparser above, it could be helpful to document, when this workaround is no longer needed.

2023-11-14 13:11 UTC, sallner commented on src/lingua/extractors/babel.py
> +
See above.

2023-11-15 21:34 UTC, arkid15r reviewed
Hi @sallner, thanks for reviewing this!

2023-11-15 21:34 UTC, arkid15r commented on src/lingua/extract.py
>      from ConfigParser import SafeConfigParser
Could you provide an example?

2023-11-24 02:23 UTC, arkid15r commented
I've bumped into one more lingua issue that needs to be fixed 🤷‍♂️ 

Taking into account there has been no activity on the project for more than 18 months it may be a good idea to branch out a new project and use it for further development. Need to look into the license for details. Keeping this open for another week or two.

2023-12-04 11:59 UTC, htgoebel requested changes
Thanks for this update.
@wichert Can you please merge this and provide a new release.Thanks.

2023-12-04 11:59 UTC, htgoebel commented on .github/workflows/test.yaml
> +        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
I'd keep Python 3.7 if test still pass. Even if 3.7 is EOL there might be old code out there using it.

2023-12-04 11:59 UTC, htgoebel commented on src/lingua/extract.py
>      from ConfigParser import SafeConfigParser
Since lingua is Python 3 only, the `except`-case can be removed. The module is called `configparser` since Python 3.0.

2023-12-04 11:59 UTC, htgoebel commented on src/lingua/extractors/__init__.py
> +    from importlib_metadata import entry_points
```suggestion
try:
    from importlib.metadata import entry_points
except ImportError:  # required up to Python 3.9
    from importlib_metadata import entry_points
```
At least AFAIU https://docs.python.org/3.9/library/importlib.metadata.html#entry-points and the "Compatibility Note" in https://docs.python.org/3.10/library/importlib.metadata.html#entry-points

2024-03-20 17:40 UTC, arkid15r commented
Closing in favor of https://github.com/vacanza/lingva/pull/1

2024-03-20 17:40 UTC, closed without merging